from playwright.sync_api import Playwright
from datetime import datetime
import pytest_playwright
import pytest


def test_platform_creation(playwright:Playwright):
    browser = playwright.chromium.launch()
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://admin-test.granitestack.ai/admin/login")
    page.locator("input[name=\"email\"]").click()
    page.locator("input[name=\"email\"]").fill("rahul.ranjan@thoughts2binary.com")
    page.locator("input[name=\"password\"]").click()
    page.locator("input[name=\"password\"]").fill("Rahul@123")
    page.get_by_role("button", name="Sign In").click()
    page.get_by_text("Platform Admin").click()
    page.locator("button").filter(has_text="Rahul").click()
    page.get_by_role("button", name="G Gstack").click()
    page.get_by_role("button", name="Create New Project Start").click()
    page.locator("input[name=\"name\"]").click()
    unique_name = "user_" + datetime.now().strftime("%Y%m%d%H%M%S")
    page.locator("input[name=\"name\"]").fill(unique_name)
    page.locator("input[name=\"description\"]").click()
    page.locator("input[name=\"description\"]").fill("Test")
    page.get_by_role("button", name="Build from Scratch").click()
    # page.get_by_role("button", name="Close").click()
    # page.get_by_role("textbox", name="Enter Prompt Query").fill("E commerce platform\n")
    # page.get_by_role("button", name="Open Drop").nth(3).click()
    # page.get_by_role("button", name="Convert To Tenant Type").click()
    # page.get_by_role("button", name="Yes").click()
    # page.get_by_role("button", name="Open Drop").nth(4).click()
    # page.get_by_role("button", name="notes Manage Notes").click()
    # page.get_by_role("textbox").click()
    # page.get_by_role("textbox").fill("N1")
    # page.locator(".StyledCheckBox__StyledCheckBoxKnob-sc-1dbk5ju-5.eFiPEg").click()
    # page.get_by_role("button", name="Save").click()
    # page.get_by_role("button", name="Open Drop").nth(4).click()
    # page.get_by_role("button", name="audit Enable Audit Trail").click()
    # page.get_by_role("button", name="documents Manage Document").click()
    # page.locator("input[name=\"documentConfig.0.type\"]").click()
    # page.locator("input[name=\"documentConfig.0.type\"]").fill("D1")
    # page.locator(".multi-select-text-input__value-container").click()
    # page.locator("#react-select-7-input").fill("D11")
    # page.locator(".StyledCheckBox__StyledCheckBoxKnob-sc-1dbk5ju-5.eFiPEg").click()
    # page.get_by_role("button", name="Save").click()
    # page.get_by_role("button", name="Open Drop").nth(4).click()
    # page.get_by_role("button", name="Enable Tasks").click()
    # page.get_by_role("button", name="Enable Survey").click()
    # page.get_by_role("button", name="FormClose").nth(1).click()
    # page.locator("div:nth-child(7) > .StyledBox-sc-13pk1d4-0").first.click()
    # page.get_by_role("dialog").click()
    # page.get_by_role("button", name="Close").click()
    # page.locator("button").filter(has_text="Deploy Beta").click()
    # page.get_by_role("button", name="Yes").click()
    # page.locator(
    #     ".StyledBox-sc-13pk1d4-0.gXNkSA.FormField__FormFieldBox-sc-m9hood-0.kzJfVF.sc-jwWbkn.jXjJaI > .StyledBox-sc-13pk1d4-0.eipxaN > .sc-eLtQCx > .sc-fBWQRz > .select__control > .select__value-container").click()
    #